#!/bin/bash
if [ $# -eq 0 ]; then
	echo "Incorrect Syntax"
	echo "upload <filename>"
	exit 1
fi

if [ $# -eq 1 ]; then
	FILE="$1"
	curl -H"cmdline:true" -F filedata=@$FILE http://files.elmnts.co/upload
fi

if [ $# -eq 2 ]; then
	if [ $1 == "-d" ]; then
		FILE="$2"
		curl -H"cmdline:true" -H"selfdestruct:true" -F filedata=@$FILE http://files.elmnts.co/upload
	fi
fi